# PR Labeler configuration
# Automatically labels PRs based on changed files

# Core MCP functionality
"area: mcp":
  - changed-files:
      - any-glob-to-any-file: 'src/mcp/**'

# A2A Protocol
"area: a2a":
  - changed-files:
      - any-glob-to-any-file: 'src/a2a/**'

# Memory system
"area: memory":
  - changed-files:
      - any-glob-to-any-file: 'src/memory/**'
      - any-glob-to-any-file: 'src/knowledge-graph/**'

# Agent system
"area: agents":
  - changed-files:
      - any-glob-to-any-file: 'src/agents/**'

# Orchestrator
"area: orchestrator":
  - changed-files:
      - any-glob-to-any-file: 'src/orchestrator/**'

# Core functionality
"area: core":
  - changed-files:
      - any-glob-to-any-file: 'src/core/**'

# Evolution system
"area: evolution":
  - changed-files:
      - any-glob-to-any-file: 'src/evolution/**'

# Telemetry & Logging
"area: telemetry":
  - changed-files:
      - any-glob-to-any-file: 'src/telemetry/**'

# Internationalization
i18n:
  - changed-files:
      - any-glob-to-any-file: 'src/i18n/**'

# Planning system
"area: planning":
  - changed-files:
      - any-glob-to-any-file: 'src/planning/**'

# MCP Tools (specific tool definitions)
"area: tools":
  - changed-files:
      - any-glob-to-any-file: 'src/mcp/tools/**'
      - any-glob-to-any-file: 'src/tools/**'

# CI/CD
"area: ci":
  - changed-files:
      - any-glob-to-any-file: '.github/**'

# Documentation
documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: 'docs/**'

# Tests
test:
  - changed-files:
      - any-glob-to-any-file: '**/*.spec.ts'
      - any-glob-to-any-file: '**/*.test.ts'
      - any-glob-to-any-file: 'tests/**'

# Configuration
config:
  - changed-files:
      - any-glob-to-any-file: '*.config.*'
      - any-glob-to-any-file: 'tsconfig*.json'
      - any-glob-to-any-file: '.eslint*'

# Scripts
scripts:
  - changed-files:
      - any-glob-to-any-file: 'scripts/**'
