# GitHub Labels Configuration for Claude Code Buddy
# Apply with: gh label create "name" --description "desc" --color "color"

# Type Labels
- name: bug
  color: "d73a4a"
  description: Something isn't working

- name: enhancement
  color: "a2eeef"
  description: New feature or request

- name: documentation
  color: "0075ca"
  description: Improvements or additions to documentation

- name: refactor
  color: "fbca04"
  description: Code refactoring without functional changes

- name: performance
  color: "5319e7"
  description: Performance improvements

- name: security
  color: "ee0701"
  description: Security related changes

- name: test
  color: "bfd4f2"
  description: Test improvements

# Priority Labels
- name: "priority: critical"
  color: "b60205"
  description: Needs immediate attention

- name: "priority: high"
  color: "d93f0b"
  description: Important, should be addressed soon

- name: "priority: medium"
  color: "fbca04"
  description: Normal priority

- name: "priority: low"
  color: "0e8a16"
  description: Nice to have

# Status Labels
- name: triage
  color: "ededed"
  description: Needs triage

- name: "status: blocked"
  color: "b60205"
  description: Blocked by another issue or external factor

- name: "status: in progress"
  color: "0052cc"
  description: Currently being worked on

- name: "status: needs review"
  color: "6f42c1"
  description: Needs code review

- name: "status: ready"
  color: "0e8a16"
  description: Ready to be picked up

# Component Labels (CCB specific)
- name: "area: mcp"
  color: "c5def5"
  description: MCP Server and tools

- name: "area: a2a"
  color: "c5def5"
  description: A2A Protocol (agent-to-agent)

- name: "area: memory"
  color: "c5def5"
  description: Memory and Knowledge Graph

- name: "area: agents"
  color: "c5def5"
  description: Agent system

- name: "area: orchestrator"
  color: "c5def5"
  description: Task orchestration

- name: "area: core"
  color: "c5def5"
  description: Core functionality

- name: "area: evolution"
  color: "c5def5"
  description: Evolution system

- name: "area: telemetry"
  color: "c5def5"
  description: Telemetry and logging

- name: "area: planning"
  color: "c5def5"
  description: Planning system

- name: "area: tools"
  color: "c5def5"
  description: MCP tool definitions

- name: "area: ci"
  color: "c5def5"
  description: CI/CD and GitHub Actions

- name: i18n
  color: "bfdadc"
  description: Internationalization and translations

# Dependency Labels
- name: dependencies
  color: "0366d6"
  description: Dependency updates

- name: npm
  color: "cb3837"
  description: NPM package updates

- name: github-actions
  color: "2088ff"
  description: GitHub Actions updates

# Special Labels
- name: "good first issue"
  color: "7057ff"
  description: Good for newcomers

- name: "help wanted"
  color: "008672"
  description: Extra attention is needed

- name: duplicate
  color: "cfd3d7"
  description: This issue or PR already exists

- name: wontfix
  color: "ffffff"
  description: This will not be worked on

- name: breaking-change
  color: "b60205"
  description: Introduces breaking changes

- name: mcp-compliance
  color: "1d76db"
  description: MCP specification compliance

- name: config
  color: "d4c5f9"
  description: Configuration changes

- name: scripts
  color: "fef2c0"
  description: Scripts and tooling
