name: Bug Report
description: Report a bug in Claude Code Buddy
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!
        Please fill out the form below to help us investigate.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - MCP Server
        - MCP Tools (buddy-do, buddy-remember, etc.)
        - A2A Protocol
        - Memory System
        - Knowledge Graph
        - Agents
        - Orchestrator
        - Installation/Setup
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: |
        When I tried to...
        Expected: ...
        Actual: ...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Configure CCB with...
        2. Call the tool...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Any error messages or logs
      render: shell
      placeholder: |
        Paste error messages or logs here

  - type: input
    id: version
    attributes:
      label: CCB Version
      description: Run `npm list @pcircle/claude-code-buddy-mcp`
      placeholder: "2.5.3"
    validations:
      required: true

  - type: dropdown
    id: client
    attributes:
      label: Claude Code Client
      description: Which client are you using?
      options:
        - Claude Code CLI
        - Cursor
        - VS Code
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node --version`
      placeholder: "v20.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: textarea
    id: mcp-config
    attributes:
      label: MCP Configuration
      description: Your MCP configuration (remove sensitive info)
      render: json
      placeholder: |
        {
          "mcpServers": {
            "claude-code-buddy": {
              "command": "npx",
              "args": ["-y", "@pcircle/claude-code-buddy-mcp"]
            }
          }
        }

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information that might help
