name: Security Vulnerability
description: Report a security vulnerability (will be redirected to private reporting)
title: "[Security]: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ STOP - Do Not Report Security Vulnerabilities Here!

        **Public issues are not the right place for security vulnerabilities.**

        For the safety of all users, please report security issues privately.

  - type: markdown
    attributes:
      value: |
        ## How to Report Security Vulnerabilities

        Please use one of these **private** reporting methods:

        ### Option 1: GitHub Security Advisories (Recommended)

        👉 [Report privately via GitHub Security Advisories](https://github.com/PCIRCLE-AI/claude-code-buddy/security/advisories/new)

        This is the preferred method as it allows us to coordinate the fix privately.

        ### Option 2: Email

        📧 Send an email to: **security@memesh.ai**
        Or: **support@pcircle.ai** with subject "SECURITY VULNERABILITY"

  - type: markdown
    attributes:
      value: |
        ## What to Include in Your Report

        Please provide:

        - **Description** of the vulnerability
        - **Steps to reproduce** the issue
        - **Potential impact** assessment
        - **Suggested fix** (if you have one)
        - **Your contact information** for follow-up

  - type: markdown
    attributes:
      value: |
        ## What to Expect

        - **Acknowledgment**: Within 48 hours
        - **Initial Assessment**: Within 5 business days
        - **Resolution Timeline**:
          - Critical: 24-48 hours
          - High: 3-7 days
          - Medium: 7-14 days
          - Low: Next scheduled release

        See our [Security Policy](https://github.com/PCIRCLE-AI/claude-code-buddy/blob/main/SECURITY.md) for more details.

  - type: markdown
    attributes:
      value: |
        ## Responsible Disclosure

        We appreciate responsible disclosure of security vulnerabilities and commit to:

        - ✅ Acknowledge your report promptly
        - ✅ Keep you informed of progress
        - ✅ Credit you in security advisories (if desired)
        - ✅ Work with you to ensure proper resolution

        Thank you for helping keep MeMesh and its users safe! 🛡️

  - type: checkboxes
    id: confirm
    attributes:
      label: I Understand
      description: Please confirm you understand how to report security issues
      options:
        - label: I will report this security issue privately (not here)
          required: true
        - label: I have read the Security Policy
          required: true

  - type: textarea
    id: redirect
    attributes:
      label: Next Steps
      description: |
        This public issue will be closed immediately.
        Please use one of the private reporting methods above.
      value: |
        🔒 Closing this issue - please report via private channels.

        Use:
        - GitHub Security Advisories: https://github.com/PCIRCLE-AI/claude-code-buddy/security/advisories/new
        - Email: security@memesh.ai
    validations:
      required: false
